### ISSUE TITLE
Segmentation fault in WAV generation

### ISSUE THREAD

**Issue by kl2792** [CSTR-Edinburgh/merlin#168] opened 2017-06-19 16:40 UTC
Hi all,

I've set up and run my files and directories in Merlin, but upon the final step of WAV generation, I always receive the following error: 

```
2017-06-02 10:43:42,417 INFO     wav_generation: creating waveform for 1096 of 1262: tr0394f_appwrd37
2017-06-02 10:43:43,192 CRITICAL     subprocess: exit status -11
2017-06-02 10:43:43,193 CRITICAL     subprocess:  for command: /homes/kl2792/merlin/tools/bin/WORLD/synth 1024 16000 tr0394f_appwrd37.f0 tr0394f_appwrd37.sp tr0394f_appwrd37.ap tr0394f_appwrd37.wav
2017-06-02 10:43:43,193 CRITICAL     subprocess:       stderr:
2017-06-02 10:43:43,193 CRITICAL     subprocess:       stdout:
2017-06-02 10:43:43,193 CRITICAL     subprocess: OSError for /homes/kl2792/merlin/tools/bin/WORLD/synth 1024 16000 tr0394f_appwrd37.f0 tr0394f_appwrd37.sp tr0394f_appwrd37.ap tr0394f_appwrd37.wav
Traceback (most recent call last):
  File "/homes/kl2792/merlin/src/run_merlin.py", line 1175, in <module>
    main_function(cfg)
  File "/homes/kl2792/merlin/src/run_merlin.py", line 961, in main_function
    generate_wav(gen_dir, gen_file_id_list, cfg)     # generated speech
  File "/homes/kl2792/merlin/src/utils/generate.py", line 281, in generate_wav
    .format(synworld=WORLD['SYNTHESIS'], fl=cfg.fl, sr=cfg.sr, f0=files['f0'], sp=files['sp'], ap=files['ap'], wav=files['wav']))
  File "/homes/kl2792/merlin/src/utils/generate.py", line 93, in run_process
    raise OSError
OSError
```

There appear to be instances of this error with other utterances as well, because when I remove the specified utterance, I receive the same error on others. When I run the command specified, `~/merlin/tools/bin/WORLD/synth 1024 16000 tr0394f_appwrd37.f0 tr0394f_appwrd37.sp tr0394f_appwrd37.ap tr0394f_appwrd37.wav`, I receive a segmentation fault.

The label, utterance, and WAV files appear to be normal, but one thing that I've noticed is that I've only been receiving the error on single-word utterances ('not', 'position', etc.) with WAV file lengths of around 2-3 seconds.

Does anybody know of what might be causing this, or of ways to fix this problem?

Thanks!

**Comment by bajibabu** [comment] 2017-06-20 07:30
Can you check the f0 file using sptk's x2x command. Perhaps there are no voiced frames since the utterance length is very small.

**Comment by b-schnell** [comment] 2017-08-31 07:18
The error is caused by the WORLD vocoder, so it's not a merlin problem. It seems that WORLD handles an F0 value of 0.0 as silence, but small values different than that will cause a segfault. Merlin does some preprocessing during audio generation where it treats LF0 values of -1e10 as silence and converts them to a F0 value of 0.0. So manually correcting some LF0 values

_lf0[lf0 <= math.log(20)] = -1e10_

fixed it for me.

**Comment by ronanki** [comment] 2017-08-31 11:02
Thank you for pointing out. It's been fixed now in [acoustic decomposition function](https://github.com/CSTR-Edinburgh/merlin/blob/master/src/frontend/parameter_generation.py#L173-L174).

**Closed by ronanki** 2017-08-31 11:02 UTC
